# -*- coding: utf-8 -*-
"""algoritmoGenético

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YDCC32WXIU5PtLC4GKyfn7v7AQItlSQq

**Algoritmo Genético - Murilo Lucena**
"""

import random
import math
import matplotlib.pyplot as plt

## Definição das Variáveis de Decisão

n_individuos = 30
quant_genes = 30
var_min = -30
var_max = 30

taxa_cruzamento = 0.9
taxa_mutacao = 0.1

geracoes = 200

## Aqui definimos que "os N melhores individuos já ficam garantidos para a próxima geração (ELITISMO)"
individuos_elite = 2

## Cruzamento por um ponto (1P) ou por dois pontos (2P)
tipo_cruzamento = "2P"

## Funções objetivos ("sphere", "rastrigin" e "rosenbrock")
funcao_objetivo = "rastrigin"

## Tipos de Seleção ("roleta" ou "torneio")
tipo_selecao = "roleta"

## Definição da primeira população

def gerar_populacao_inicial():
  populacao = []
  for i in range(n_individuos):
    cromossomo = random.choices(range(var_min, var_max), k= quant_genes)
    populacao.append(cromossomo)
    print(cromossomo)
  return populacao

## Definição da função objetivo

def sphere(x):
    """
    Sphere Function
    Mínimo global: f(0, ..., 0) = 0
    """
    return sum(xi**2 for xi in x)


def rastrigin(x):
    """
    Rastrigin Function
    Mínimo global: f(0, ..., 0) = 0
    """
    n = len(x)
    return 10*n + sum(xi**2 - 10*math.cos(2 * math.pi * xi) for xi in x)

def rosenbrock(x):
    """
    Rosenbrock Function
    Mínimo global: f(1, ..., 1) = 0
    """
    return sum(100 * (x[i+1] - x[i]**2)**2 + (x[i] - 1)**2 for i in range(len(x)-1))

def avaliar(cromossomo):
    if funcao_objetivo == "sphere":
        return sphere(cromossomo)
    elif funcao_objetivo == "rastrigin":
        return rastrigin(cromossomo)
    elif funcao_objetivo == "rosenbrock":
        return rosenbrock(cromossomo)
    else:
        raise ValueError("Função inválida")

## Definições de Cruzamentos (1P e 2P) e Mutação

def crossover_1_ponto(pai1, pai2):
    ponto = random.randint(1, len(pai1) - 1)
    return pai1[:ponto] + pai2[ponto:]


def crossover_2_pontos(pai1, pai2):
    p1 = random.randint(1, len(pai1) - 2)
    p2 = random.randint(p1 + 1, len(pai1) - 1)
    return pai1[:p1] + pai2[p1:p2] + pai1[p2:]


def cruzamento(pai1, pai2, tipo="1P"):
    if tipo == "1P":
        return crossover_1_ponto(pai1, pai2)
    elif tipo == "2P":
        return crossover_2_pontos(pai1, pai2)
    else:
        raise ValueError("Tipo de Cruzamento inválido")


def mutacao(cromossomo):
    novo = cromossomo[:]
    idx = random.randint(0, len(novo) - 1)
    novo[idx] = random.randint(var_min, var_max)
    return novo

## Definição do tipo de seleção

def selecao_torneio(populacao_avaliada, k=3):
    participantes = random.sample(populacao_avaliada, k)
    participantes.sort(key=lambda x: x[1])
    return participantes[0][0]

def selecao_roleta(populacao_avaliada):
    fitness = [1 / (ind[1] + 1e-6) for ind in populacao_avaliada]
    soma = sum(fitness)
    probs = [f / soma for f in fitness]
    escolhido = random.choices(populacao_avaliada, weights=probs, k=1)[0]
    return escolhido[0]

def selecionar(populacao_avaliada):
    if tipo_selecao == "torneio":
        return selecao_torneio(populacao_avaliada)
    elif tipo_selecao == "roleta":
        return selecao_roleta(populacao_avaliada)
    else:
        raise ValueError("Seleção inválida")

def algoritmo_genetico():


    ## Passo 1 - Gerar a população inicial

    populacao = gerar_populacao_inicial()

    historico = []
    historico_medias = []
    historico_populacao = []

    ## Passo 6 - Para cada época, faça até:
    for epoca in range(geracoes):

        ## Passo 2 - Avalie a população criada:
        populacao_avaliada = [(c, avaliar(c)) for c in populacao]
        populacao_avaliada.sort(key=lambda x: x[1])

        fitness_geracao = [ind[1] for ind in populacao_avaliada]

        melhor = populacao_avaliada[0]

        historico.append(melhor[1])
        historico_medias.append(sum(fitness_geracao) / len(fitness_geracao))
        historico_populacao.append(fitness_geracao)

        print(f"Geração {epoca} | Melhor: {melhor[1]} | Média: {historico_medias[-1]}")

        elite = [ind[0] for ind in populacao_avaliada[:individuos_elite]]

        nova_populacao = elite[:]

        ## Passo 3 - Selecionar os indivíduos mais aptos:
        while len(nova_populacao) < n_individuos:

            p1 = selecionar(populacao_avaliada)
            p2 = selecionar(populacao_avaliada)

            ## Passo 4 - Gerar novos indivíduos através do cruzamento e mutação:
            if random.random() < taxa_cruzamento:
                filho = cruzamento(p1, p2)
            else:
                filho = p1[:]

            nova_populacao.append(filho)

        for i in range(individuos_elite, len(nova_populacao)):
            if random.random() < taxa_mutacao:
                nova_populacao[i] = mutacao(nova_populacao[i])

        ## Passo 5 - Gerar nova população
        populacao = nova_populacao

    return historico, historico_medias, historico_populacao

historico, historico_medias, historico_populacao = algoritmo_genetico()

plt.figure()
plt.plot(historico, label="Melhor Fitness")
plt.plot(historico_medias, label="Média Fitness")
plt.xlabel("Geração")
plt.ylabel("Fitness")
plt.title("Evolução do Fitness")
plt.legend()
plt.grid()
plt.show()

dados_boxplot = historico_populacao[::10]

plt.figure(figsize=(12,6))
plt.boxplot(dados_boxplot)
plt.xlabel("Gerações (x10)")
plt.ylabel("Fitness")
plt.title("Distribuição do Fitness por Geração")
plt.grid()
plt.show()